def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline{
    agent any
    tools{
        maven "MAVEN3"
        jdk "JDK"
    }
    environment{

        ecs_cluster_name = "production"
        service_name = "PRODUCTION-SERVICE"

    }

    stages{
        
        stage("Deploy to ECS Production"){
            steps{
               withAWS(credentials: "cicdjenkins",region: "us-east-1" ){
                // force to delete old container deploy new one via service
                sh 'aws ecs update-service --cluster ${ecs_cluster_name} --service ${service_name} --force-new-deployment'
               }
            }

        }
    }
    post {
    always {
        echo 'Slack Notifications.'
        slackSend channel: '#jenkins',
            color: COLOR_MAP[currentBuild.currentResult],
            message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
            }
    }
}
